### ISSUE TITLE
how to use avaje-inject-test for javalin

### ISSUE THREAD

**Issue by ponyjoy** [avaje/avaje-http#109]
I can't get WebRoutes when I use avaje-inject-test to test the javalin application. 
TestJavalinFactory.java
``` java

@Factory
@TestScope
public class TestJavalinFactory {
    BeanScope beanScope;

    TestJavalinFactory(BeanScope beanScope) {
        this.beanScope = beanScope;
    }

    @Bean
    public Javalin creatTestApp() {
        Javalin app = Javalin.create();
        //LineNumber 24:   NPE　　
        List<WebRoutes> webRoutes = beanScope.list(WebRoutes.class);
        app.routes(() -> webRoutes.forEach(WebRoutes::registerRoutes));
        return app;
    }
}
```
MainTestCase.java
```java
@InjectTest
public class MainTestCase {
    @Inject
    static Javalin javalin;

    @Test
    public void testHello() {
        JavalinTest.test(javalin, (server, client) -> {
            Response response = client.get("/hello");
            Assertions.assertEquals(200, response.code());
            Assertions.assertEquals("hello!", response.body().string());
        });
    }
}
```
When I run the test, I got error:
```java
java.lang.NullPointerException
	at io.avaje.inject.spi.DBeanScopeProxy.list(DBeanScopeProxy.java:60)
	at nxu.it.TestJavalinFactory.creatTestApp(TestJavalinFactory.java:24)
	at nxu.it.TestJavalinFactory$DI.build_creatTestApp(TestJavalinFactory$DI.java:31)

```

the test project repository is here, can you take time to look at it, thanks @rbygrave 
this is demo project repository 
https://github.com/ponyjoy/javalin-test-demo
[https://github.com/ponyjoy/javalin-test-demo](url)

**Comment by SentryMan** [comment]
If you are making Javalin itself into a bean you can just wire the WebRoutes directly into the bean method.

```
@Factory
@TestScope
public class TestJavalinFactory {

    @Bean
    public Javalin creatTestApp(List<WebRoutes> webRoutes) {
        Javalin app = Javalin.create();
        app.routes(() -> webRoutes.forEach(WebRoutes::registerRoutes));
        return app;
    }
}
```

**Comment by SentryMan** [comment]
I also have an example repo that has test. https://github.com/SentryMan/avaje-javalin-api-example

**Comment by ponyjoy** [comment]
t

> If you are making Javalin itself into a bean you can just wire the WebRoutes directly into the bean method.
> 
> ```
> @Factory
> @TestScope
> public class TestJavalinFactory {
> 
>     @Bean
>     public Javalin creatTestApp(List<WebRoutes> webRoutes) {
>         Javalin app = Javalin.create();
>         app.routes(() -> webRoutes.forEach(WebRoutes::registerRoutes));
>         return app;
>     }
> }
> ```
thans for your help, I've tried injecting List<WebRoutes> before, but I get the following error：
java: No dependency provided for io.avaje.http.api.WebRoutes on io.javalin.Javalin

**Comment by ponyjoy** [comment]
> I also have an example repo that has test. https://github.com/SentryMan/avaje-javalin-api-example

@SentryMan 
I move TestJavalinFactory from test folder to src folder, and remove @TestScore annotation, it  works!
Thanks
