### ISSUE TITLE
Let Class level @Roles annotation be inheritable.

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-http#124]
Consider this class
```
@Controller
@Roles(AppRole.ADMIN)
public class ControllerClass {

  @Put("/put")
  public String put() {
  }

  @Get("/get")
  @Roles({AppRole.USER})
  public String get() {
  }
}
```
this generates

```
    ApiBuilder.put("/put", ctx -> {
    //whatever
    }, ADMIN);

    ApiBuilder.get("/get", ctx -> {
    //whatever
    }, USER);
```
# How I think it should generate
I think it should add the controller level role  like this
```
    ApiBuilder.put("/put", ctx -> {
    //whatever
    }, ADMIN);

    ApiBuilder.get("/get", ctx -> {
    //whatever
    }, USER, ADMIN);
```
Thoughts?

**Comment by rbygrave** [comment]
> Thoughts?

This change makes sense to me in that I think it would be more expected to include the class level role.

IF someone does not want that in that and instead they want to _override_ the roles on a per method/endpoint basis then they just need to remove the controller level role. I think that is pretty reasonable.
