### ISSUE TITLE
Support Body/Parameter Validation

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-http#127]
It looks like we only have validation for Bean Params? Would be nice if we could also have it for request bodies at least. Support for validating path param and query params would be nice as well.

**Comment by SentryMan** [comment]
I need ideas on how we could add param validations. Body was simple, but I'm drawing a blank here

**Comment by rbygrave** [comment]
I personally don't think we need validation on path parameters. For them they get type conversion (and can fail that) or at least for Nima and Jex the path parameters can use a regex (for example, ensure only digits for a long/int etc).

For query parameters, these also get type conversion but the difference is that they are expected to allow null (as they are query parameters and not path parameters and we use `@Default` if we need a value).

So for me I don't see the need for the code generation to add any extra validation for path or query parameters other that what they all ready do.

Do you have a specific use case you have in mind that needs validation on a query parameter say? Not keen to just have that validation as something the dev adds to the controller code?

**Comment by SentryMan** [comment]
It's more of a convenience thing. Would be nice to auto-generate instead of writing a whole validation code.

**Comment by rbygrave** [comment]
Do you have an example? A query parameter that is an email address or something?  (Email address probably isn't a good example).  Then mock it up by hand as to what the generated code should look like (and deal with null query parameters)?

**Comment by SentryMan** [comment]
Oof, bested yet again with facts and logic. In any case, we got the body parameter validation working so I'm good for now.
