### ISSUE TITLE
COMPILATION ERROR : 

### ISSUE THREAD

**Issue by kevin70** [avaje/avaje-http#161]
Hello, I also want to participate in the work of `avaje-http` modification. This project is very cool and I have been following it.

I now encountered the following errors when building the checked out project with `mvn clean package`. I tried some solutions, but always encountered new problems, so I want to return to the original state. It seems a little difficult for me now. I don't know how the current build tool configuration works. Can you give me some help or a development manual?

Thanks.

---

OS Version: `Windows 10`
Java Version: `jdk-17.0.4.1+1`

Error Message:
```
[INFO] 
[INFO] ---------------< io.avaje:avaje-http-javalin-generator >----------------
[INFO] Building avaje-http-javalin-generator 1.28-SNAPSHOT               [6/16]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ avaje-http-javalin-generator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ avaje-http-javalin-generator ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to D:\projects\avaje-http\http-generator-javalin\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] module not found: jakarta.validation
[ERROR] module not found: jakarta.inject
[ERROR] module not found: java.validation
[ERROR] module not found: io.swagger.v3.oas.annotations
[ERROR] module not found: io.avaje.http.api
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
```

**Comment by SentryMan** [comment]
mvn clean package is how I usually do it.

**Comment by kevin70** [comment]
Sorry. I found the reason. It may be that I accidentally disabled the `module-info.shade` configuration in the IDE.

**Comment by rbygrave** [comment]
Yeah, this could be confusing for folks building from source.  We need to use:
``` 
mvn clean package 
```
...due to the shading that goes on with the module-info now that we are using avaje-prisms.
