### ISSUE TITLE
`ServerContext`'s request() and response() methods are not accessible.

### ISSUE THREAD

**Issue by LoonyRules** [avaje/avaje-http#208]
The `ServerContext` class has 2 methods:
- `<T> T request() { ... }`
- `<T> T response() { ... }`
but they are not accessible outside of its package, meaning the end user cannot use them. These need to be public methods instead.

**Comment by rob-bygrave** [comment]
> not accessible outside of its package

This could be a nice little change to do.  Do you want to submit a PR?
