### ISSUE TITLE
javalin http server generator not parsing path enums 

### ISSUE THREAD

**Issue by literallyEllie** [avaje/avaje-http#221]
Hello 😄 

Having issues putting enums in the path. I am pretty sure I am not doing anything wrong, according to the [type conversions section in the docs.](https://avaje.io/http/#type-conversions)

Here is an example of the endpoint, where Preference is an enum defined in another subproject.

```java
@Controller("/profile/{playerId}/preferences")
public class PreferenceController {

  @Get("/{preference}")
  public PreferenceOption getPreference(UUID playerId, Preference preference) { .. }
```

But it generates this code,
```java
    ApiBuilder.get("/profile/{playerId}/preferences/{preference}", ctx -> {
      ctx.status(200);
      var playerId = asUUID(ctx.pathParam("playerId"));
      var preference = java.util.Objects.toString(ctx.pathParam("preference")); // not parsed into the enum
      var result = controller.getPreference(playerId, preference); // error here, expecting enum
      ctx.json(result);
    });
```

The error being:
```error
error: incompatible types: String cannot be converted to Preference
      var result = controller.getPreference(playerId, preference);
                                                      ^`
```

Sorry if I misunderstood something, but I think it is theoretically correct.

I am using
- io.javalin:javalin:5.5.0
- io.avaje:avaje-http-api:1.40
- io.avaje:avaje-inject-generator:9.2
- io.avaje:avaje-http-javalin-generator:1.40

Thank you 😄

**Comment by SentryMan** [comment]
real quick, change the enum it into a query param and see if it generates the correct mapping

**Comment by SentryMan** [comment]
I guess when we first implemented it was for query params/headers/literally anything except path. I know how to fix it. Will get it out as soon as I can.
