### ISSUE TITLE
Deprecate avaje-http-generator-helidon (effectively replaced going forward by avaje-http-generator-nima)

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-http#237]
It very much looks like Helidon is going to replace ALL the netty based components with Nima / Virtual Threads based ones.

I believe our current name `avaje-generator-helidon` is going to be confusing for people going forward.

I think we should rename  _avaje-generator-helidon_ -> _avaje-generator-reactive-helidon_. I personally don't think this generator will get much use going forward to the point that we could actually deprecate it given that Helidon themselves are going all in on Nima and Virtual Threads.

We could then consider renaming avaje-generator-nima -> avaje-generator-helidon ... if we thought that "Nima" would be less well known/understood?

**Comment by SentryMan** [comment]
We could probably do this in 2.0

**Comment by SentryMan** [comment]
I for one think we should deprecate it

**Comment by rob-bygrave** [comment]
> I for one think we should deprecate it

I agree. 

I'm thinking something like rename the module to say `deprecated-helidon-generator`, leave it in the git repo as source code but stop actually releasing it to central.  See who complains and asks for it to be released.
