### ISSUE TITLE
Q: Using factory methods for building POJO when using Immutables.org

### ISSUE THREAD

**Issue by macabrus** [avaje/avaje-http#269]
Not sure where to ask question so I'll post here but is my understanding correct here:
codegen doesn't support factory methods for Immutables.org (ideally I'd delegate this to Jackson object mapper to map since it can be configured to use builder methods). For now, my code is:
```java
@Post
    public User addUser(@Header("App-User") UUID principalId, @Form CreateUser dto) {
        return userService.add(CreateUserCommand.builder()
            .principal(userService.get(principalId))
            .dto(dto)
            .build()
        );
    }
```
which translates into:
```java
ApiBuilder.post("/user", ctx -> {
      ctx.status(201);
      var principalId = toUUID(ctx.header("App-User"));
      var dto =  new CreateUser(
        ctx.formParam("firstName"), 
        ctx.formParam("lastName"), 
        ctx.formParam("email"), 
        toInstant(ctx.formParam("dateJoined"))
      );
      dto.hashCode = asInt(checkNull(ctx.formParam("hashCode"), "hashCode"));

      var result = controller.addUser(principalId, dto);
      ctx.json(result);
    });
```

where CreateUser is instance of Immutables.org dataclass. This is compile error since constructor is private on this. Is there a way to make @Form annotation generate code that uses Javalin's app-level configured object mapper?

I am POST-ing application/json request to this endpoint which could deserialize this form.

The alternative is to just inject mapper in controller and manually handle `@Form String myArg` and build object from raw string but it's clunky.

So my proposal (although I don't know if this is even possible since I am not experienced with codegen stuff) would be to allow for registering custom deserializers which override default in codegen `(selector, class) -> my custom transform` such as:
```java
public static CreateUser fromRequest(String/byte[] raw) {
   ...
}
...

Avaje.registerConverter(Form.class, CreateUser.class, MyClass::fromRequest)
```

**Comment by SentryMan** [comment]
have you tried using, 
```
@Value.Style(
    of = "new",
    allParameters = true,
)
```
to make immutables have an all-args constructor?

**Comment by SentryMan** [comment]
Also, can you share the `CreateUser` object that you are using?

**Comment by SentryMan** [comment]
I guess one other question is whether Jackson can actually deserialize `application/x-www-form-urlencoded` data into objects(given that it is not JSON), can you provide an example of what that would look like?

**Comment by macabrus** [comment]
Okay I tried adding your options to @Style and now the generated code is like:
```java
ApiBuilder.post("/user", ctx -> {
      ctx.status(201);
      var principalId = toUUID(ctx.header("App-User"));
      var dto =  new CreateUser();
      dto.firstName = ctx.formParam("firstName");
      dto.lastName = ctx.formParam("lastName");
      dto.email = ctx.formParam("email");
      dto.dateJoined = toInstant(ctx.formParam("dateJoined"));
      dto.hashCode = asInt(checkNull(ctx.formParam("hashCode"), "hashCode"));

      var result = controller.addUser(principalId, dto);
      ctx.json(result);
    });
```
which still fails to compile because dto.* is not public, it should use setters to set the properties.
My dataclass looks like:

```java
@Value.Immutable
@Value.Modifiable
public interface UserModel {
    @Nullable
    UUID getId();
    String getFirstName();
    String getLastName();
    @Email
    String getEmail();
    Instant getDateJoined();
}
```

with package-level style annotation covering it:
```java
@JsonSerialize
@Target({ElementType.PACKAGE, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Style(
    deepImmutablesDetection = true,
    get = {"is*", "get*"},
    typeAbstract = {"*Model"},
    typeModifiable = "Mutable*",
    typeImmutable = "*",
    of = "new",
    allParameters = true,
    visibility = ImplementationVisibility.PUBLIC,
    defaults = @Immutable(
        prehash = true
    )
)
public @interface ModelStyle {
}
```

**Comment by SentryMan** [comment]
From the link you shared:
> Spring is able to serialize into your POJO classes but it does not use Jackson because it isn't JSON.

still doesn't seem to directly use Jackson, so Javalin (and avaje by extension) can't use jackson to directly deserialize.

though you have indeed found a neat bug in that generated classes don't seem to work as Form/BeanParams

**Comment by SentryMan** [comment]
the way I see you've got three options. 

1. Don't use `Immutables` for `CreateUser` make it immutable the old-fashioned way using an all-args constructor and getters. This is the simplest since you don't have to do any mapping.

2. Don't use the form bean feature and construct `CreateUser` from the parameters building the immutable object manually.
```java
    @Post
    @Form //un-annotated parameters will now be assumed to be form params
    public User addUser(@Header("App-User") UUID principalId,  String firstName, String lastName, String email, Instant dateJoined) {
       CreateUser dto = //contruct the object here...
        return userService.add(CreateUserCommand.builder()
            .principal(userService.get(principalId))
            .dto(dto)
            .build()
        );
    }
```
3.  follow that SO thread and do something like this:
```java
@Post
    public User addUser(@Header("App-User") UUID principalId, Context ctx) {
        var params = ctx.formParamMap();
        CreateUser dto = ObjectMapper.CreateUser dto = ObjectMapper.convertValue(params, CreateUser.class);
        return userService.add(CreateUserCommand.builder()
            .principal(userService.get(principalId))
            .dto(dto)
            .build()
        );
    }
```

**Comment by macabrus** [comment]
Yes, that's how i resolved it, manually constructing object, the raw string approach would not generate openapi fields.

thanks for ideas @SentryMan
