### ISSUE TITLE
[http client] Add support for "error decoder" Function<HttpException, DistanceException>

### ISSUE THREAD

**Issue by rob-bygrave** [avaje/avaje-http#273]
Currently we either 

1: allow `io.avaje.http.client.HttpException` to be thrown, catch that and decode if necessary like:

```java
    } catch (HttpException e) {
      // handle error, convert to the API specific ErrorResponse
      ErrorResponse err = e.bean(ErrorResponse.class);
      UUID id = err.getId();
      Integer code = err.getCode();
      String errorMessage = err.getError();
    }
```

2: register a `RequestIntercept` and in `afterResponse()` decode the response and throw an Exception as desired

This proposal is to make this easier / nicer by:

**A)** Allowing us to register a "error decoder" that implements `Function<HttpException, Throwable>` that converts the HttpException into an application specific exception.  This would be registered with the HttpClient.Builder.

**B)** For a `@Client` annotated interface, when a method in the interface is declared to throw an Exception, generate code that converts HttpException to that interface declared Exception [look at the constructors on the exception and generate code that converts HttpException into that]. 

e.g.
```java
@Client
public interface Simple {

  @Get("users/{user}/repos")
  List<Repo> listRepos(String user, String other) throws MyApplicationException;
```
... then the generated client generates code that catches HttpException and converts it into MyApplicationException.

**Comment by rob-bygrave** [comment]
So for **B** the generated client code would look something like:

```java
  @Get("users/{user}/repos")
  @Override
  public List<Repo> listRepos(String user, String other) throws MyApplicationException {
    try {
      return context.request()
        .path("users").path(user).path("repos")
        .queryParam("other", other)
        .GET().list(Repo.class);
    } catch (HttpException e) {
      throw decodeMyApplicationException(e);
    }
  }

  private MyApplicationException decodeMyApplicationException(HttpException e) {
    var body = e.bean(MyApplicationException.MyErrorBody.class);
    return new MyApplicationException(e.statusCode(), body);
  }
```
with the try catch block and the decodeMyApplicationException() added

**Comment by SentryMan** [comment]
I'm leaning towards option B

**Comment by SentryMan** [comment]
Though I'm thinking we can do both, will prototype this tomorrow.
