### ISSUE TITLE
Kotlin: "invalid path argument"

### ISSUE THREAD

**Issue by Tijs-2** [avaje/avaje-http#47]
Hi Rob,

I was using the newest libraries (avaje-http-javalin-generator:1.0, avaje-inject-generator:2.0 ) for a small new service that I wanted to build in Kotlin but it seams not to work.

My code is:
@Controller
@Path("/zipcode")
class ZipCodeController {
    @Get("/zipcode/{zipcode}")
    @Throws(NotFoundException::class)
    fun getAddress(zipcode: String): ZipCodeResponse {
        val zipCodeResult = QZipCode().zipCode.eq(zipcode).findOne() ?: throw NotFoundException("Zipcode not found")

        return ZipCodeResponse(
            zipCodeResult.zipCode,
            zipCodeResult.streetName,
            zipCodeResult.placeOfResidence
        )
    }
}

Which then generates into a route file:
  @Override
  public void registerRoutes() {

    ApiBuilder.get("/zipcode/zipcode/:zipcode", ctx -> {
      ctx.status(200);
      String zipcode = ctx.pathParam("zipcode");
      ctx.json(controller.getAddress(zipcode));
    }); 
  }
Then i go to the webpage and i get the "invalid path argument".

If I build the same in Java it works.
Also when I use a Get without parameters it also works in kotlin.

Now I am not sure if this is a issue with this libary or with Javalin itself.

Hopefully you know where the issue lies or can point where to look futher,
Tijs

**Comment by rbygrave** [comment]
Do you have a stack trace?

We could / should add a kotlin + javalin test module - that would be good.

**Comment by Tijs-2** [comment]
Hmm... something weird happend I did not change anything except move from post back to get with the same settings as above and now it works.
I have no idea why but maybe because my computer was off for a few days. no idea....

**Comment by Tijs-2** [comment]
Hmm... i see some other weird things which seem to disappear when restarting my computer / all intellij editors so maybe it is some weird caching issue...

**Comment by rbygrave** [comment]
Ok, closing for now.
