### ISSUE TITLE
Passing Set<Role> parameter for controller method

### ISSUE THREAD

**Issue by Travisnv** [avaje/avaje-http#61]
Hi @rbygrave 

I have a question regard to passing the permitted roles into controller methods `@Get`, `@Post`, `@Put` and `@Delete`: do we support for the usage of `AccessManager` from javalin?

from `Javalin`, from setting route, we can pass a set of permitted `Role` then the configured AccessManager will be kicked in and work per endpoint setup. However, I don't see any generated code to handle Role.

Regards,
Travis

**Comment by rbygrave** [comment]
>  do we support for the usage of AccessManager from javalin?

Yes we do.  

That said, I have somehow managed to lose the documentation (it is no longer in the docs, I must have lost it when I re-organised the documentation a while back).


Example:
https://github.com/avaje/avaje-http/blob/master/tests/test-javalin/src/main/java/org/example/myapp/web/HelloController.java#L58
```java
  @Roles({AppRoles.ADMIN, AppRoles.BASIC_USER})
  @Get("/:id/:date")
  HelloDto hello(int id, LocalDate date, String otherParam) {
  ...
```

Generated  code for that is:
```java
    ApiBuilder.get("/hello/:id/:date", ctx -> {
      ctx.status(200);
      int id = asInt(ctx.pathParam("id"));
      LocalDate date = asLocalDate(ctx.pathParam("date"));
      String otherParam = ctx.queryParam("otherParam");
      ctx.json(controller.hello(id, date, otherParam));
    }, roles(ADMIN, BASIC_USER));
```

# Steps: (I need to check but pretty sure it is these 3 steps)

## 1. Create an enum that implements `io.javalin.core.security.Role`

Example

```java
import io.javalin.core.security.Role;

public enum AppRoles implements Role {
  ANYONE, ADMIN, BASIC_USER, ORG_ADMIN
}
```

## 2. Create an annotation that has a short name that ends with `Roles` or  `PermittedRoles`

Example:

```java
package org.example.myapp.web;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Specify permitted roles.
 */
@Target(value={METHOD, TYPE})
@Retention(value=RUNTIME)
public @interface Roles {

  /**
   * Specify the permitted roles.
   */
  AppRoles[] value() default {};
}
```

## 3. Specify the annotation on the methods

Example

```java
  @Roles({AppRoles.ADMIN, AppRoles.BASIC_USER})
  @Get("/:id/:date")
  HelloDto hello(int id, LocalDate date, String otherParam) {
  ...
```

**Comment by rbygrave** [comment]
Assuming those steps above are correct (I am reasonably sure I haven't forgotten anything) then we need to add this back into the documentation.

**Comment by rbygrave** [comment]
Notes: I am pretty sure a future version of Javalin the roles can be passed as varargs (without needing the static SecurityUtil.roles() method).  Jex supports this same mechanism for permitted roles per endpoint and/or controller (using varargs).

**Comment by Travisnv** [comment]
Thanks for your example, three steps are clear to follow.

Cheers,
Travis

**Comment by rbygrave** [comment]
Ok, I have updated  the documentation and that is now pretty good I think.
https://avaje.io/http/#roles

I think we can close this one.
